import type { Account } from "@/types"

export const SEED_ACCOUNTS: Omit<Account, "id">[] = [
  // ── Retirement Annuities ─────────────────────────────────────────────────────
  {
    name: "Growth RA",
    provider: "Allan Gray",
    type: "retirement_annuity",
    currentBalance: 850000,
    monthlyContribution: 8500,
    expectedReturn: 10.5,
    annualFees: 0.9,
    contributionEscalation: 7,
  },
  {
    name: "Index RA",
    provider: "10X Investments",
    type: "retirement_annuity",
    currentBalance: 320000,
    monthlyContribution: 5000,
    expectedReturn: 10.0,
    annualFees: 0.55,
    contributionEscalation: 6,
  },
  {
    name: "Legacy RA",
    provider: "Old Mutual",
    type: "retirement_annuity",
    currentBalance: 182000,
    monthlyContribution: 2000,
    expectedReturn: 9.5,
    annualFees: 1.5,
    contributionEscalation: 5,
  },
  // ── Pension Funds ────────────────────────────────────────────────────────────
  {
    name: "Company Pension",
    provider: "Sanlam",
    type: "pension_fund",
    currentBalance: 1240000,
    monthlyContribution: 9500,
    expectedReturn: 9.0,
    annualFees: 1.2,
    contributionEscalation: 7,
  },
  {
    name: "Previous Employer Pension",
    provider: "Liberty",
    type: "pension_fund",
    currentBalance: 445000,
    monthlyContribution: 0,
    expectedReturn: 8.5,
    annualFees: 1.3,
    contributionEscalation: 0,
  },
  // ── Preservation Funds ───────────────────────────────────────────────────────
  {
    name: "Preservation Fund",
    provider: "Allan Gray",
    type: "preservation_fund",
    currentBalance: 378000,
    monthlyContribution: 0,
    expectedReturn: 10.5,
    annualFees: 0.9,
    contributionEscalation: 0,
  },
  {
    name: "Balanced Preservation",
    provider: "Coronation",
    type: "preservation_fund",
    currentBalance: 215000,
    monthlyContribution: 0,
    expectedReturn: 9.8,
    annualFees: 1.0,
    contributionEscalation: 0,
  },
  // ── Tax-Free Savings ─────────────────────────────────────────────────────────
  {
    name: "TFSA — Global Equity",
    provider: "Investec",
    type: "tfsa",
    currentBalance: 183000,
    monthlyContribution: 3833,
    expectedReturn: 11.0,
    annualFees: 0.5,
    contributionEscalation: 0,
    tfsaContributionsToDate: 183000,
  },
  {
    name: "TFSA — ETF Portfolio",
    provider: "EasyEquities",
    type: "tfsa",
    currentBalance: 68000,
    monthlyContribution: 1000,
    expectedReturn: 12.0,
    annualFees: 0.2,
    contributionEscalation: 0,
    tfsaContributionsToDate: 68000,
  },
  {
    name: "TFSA — Near Limit",
    provider: "ABSA",
    type: "tfsa",
    currentBalance: 510000,
    monthlyContribution: 0,
    expectedReturn: 8.0,
    annualFees: 0.75,
    contributionEscalation: 0,
    tfsaContributionsToDate: 498000,
  },
  // ── Discretionary ────────────────────────────────────────────────────────────
  {
    name: "Balanced Fund",
    provider: "Coronation",
    type: "discretionary",
    currentBalance: 495000,
    monthlyContribution: 5000,
    expectedReturn: 11.0,
    annualFees: 1.0,
    contributionEscalation: 6,
  },
  {
    name: "SA Equity ETFs",
    provider: "EasyEquities",
    type: "discretionary",
    currentBalance: 148000,
    monthlyContribution: 3000,
    expectedReturn: 12.0,
    annualFees: 0.2,
    contributionEscalation: 8,
  },
]
